apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: tz-cluster-cna2
  region: us-east-1
  version: "1.34"
  tags:
    karpenter.sh/discovery: tz-cluster-cna2

managedNodeGroups:
  - name: default
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    instanceType: t3.medium
    privateNetworking: true

addons:
  - name: vpc-cni
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
  - name: coredns
    version: latest
  - name: kube-proxy
    version: latest
  - name: aws-ebs-csi-driver
    wellKnownPolicies:
      ebsCSIController: true
  - name: amazon-cloudwatch-observability
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy