apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: claims-eks-cluster
  region: us-east-1
  version: "1.34"
  tags:
    karpenter.sh/discovery: claims-eks-cluster

iam:
  withOIDC: true

managedNodeGroups:
  - name: default
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    instanceType: t3.medium
    privateNetworking: true

addons:
  - name: eks-pod-identity-agent
  - name: vpc-cni
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
  - name: coredns
  - name: kube-proxy
  - name: aws-ebs-csi-driver
    wellKnownPolicies:
      ebsCSIController: true
  - name: amazon-cloudwatch-observability
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy